# Generated by Django 6.0.6 on 2026-06-12 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('recipe_title', models.CharField(max_length=200)),
                ('recipe_description', models.TextField(help_text='Ingredients, prep steps, etc.')),
                ('ingredients_used', models.TextField(help_text='Ingredients used from pantry (JSON/Text)')),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, help_text='Protein in grams', null=True)),
                ('carbs', models.FloatField(blank=True, help_text='Carbohydrates in grams', null=True)),
                ('fat', models.FloatField(blank=True, help_text='Fat in grams', null=True)),
                ('prepared', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField(default=1.0)),
                ('unit', models.CharField(default='pcs', help_text='e.g. g, kg, pcs, cans, cups', max_length=30)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (Little/no exercise)'), ('lightly_active', 'Lightly Active (Light exercise/sports 1-3 days/week)'), ('moderately_active', 'Moderately Active (Moderate exercise/sports 3-5 days/week)'), ('very_active', 'Very Active (Hard exercise/sports 6-7 days/week)')], default='sedentary', max_length=50)),
                ('fitness_goal', models.CharField(choices=[('lose_weight', 'Lose Weight'), ('maintain_weight', 'Maintain Weight'), ('gain_muscle', 'Gain Muscle'), ('improve_endurance', 'Improve Endurance')], default='maintain_weight', max_length=50)),
                ('diet_plan', models.CharField(choices=[('balanced', 'Balanced / Anything'), ('keto', 'Ketogenic (Low Carb, High Fat)'), ('paleo', 'Paleo'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('mediterranean', 'Mediterranean'), ('high_protein', 'High Protein')], default='balanced', max_length=50)),
                ('allergies', models.TextField(blank=True, default='', help_text='Comma-separated list of allergies or dietary restrictions')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
