# Generated by Django 6.0.6 on 2026-06-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_savedrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='category',
            field=models.CharField(choices=[('essentials', 'Essentials'), ('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('meat_seafood', 'Meat & Seafood'), ('dairy', 'Dairy'), ('grains_cereals', 'Grains & Cereals'), ('spices_condiments', 'Spices & Condiments'), ('beverages', 'Beverages'), ('snacks', 'Snacks'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
