# Generated by Django 6.0.6 on 2026-06-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pantryitem_available_pantryitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='servings',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='servings',
            field=models.IntegerField(default=2),
        ),
    ]
