# Generated by Django 6.0.6 on 2026-06-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mealplan_servings_savedrecipe_servings'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrecipe',
            name='meal_type',
            field=models.CharField(default='lunch', max_length=20),
        ),
    ]
