# Generated by Django 6.0.6 on 2026-06-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_savedrecipe_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='image_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='image_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
