# Generated by Django 6.0.6 on 2026-06-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_dailymealbundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_carbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_micro_targets',
            field=models.TextField(blank=True, default='', help_text='JSON string of micronutrient targets'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_protein',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
