# Generated by Django 6.0.6 on 2026-06-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile_custom_calories_userprofile_custom_carbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='ingredients_used',
            field=models.TextField(blank=True, default='', help_text='Ingredients used from pantry (JSON/Text)'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='recipe_description',
            field=models.TextField(blank=True, default='', help_text='Ingredients, prep steps, etc.'),
        ),
    ]
